CREATE TABLE "DeliveryOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderCity" text NOT NULL,
    "SenderAddress" text NOT NULL,
    "ReceiverCity" text NOT NULL,
    "ReceiverAddress" text NOT NULL,
    "CargoWeight" double precision NOT NULL,
    "PickupDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DeliveryOrders" PRIMARY KEY ("Id")
);


